trigger: none
pr: none

schedules:
  - cron: "30 3 * * 1-5"        # 9:00 AM IST (cron UTC)
    displayName: "Morning Run"
    always: true
    branches:
      include:
        - main                  # change to 'master' if your repo branch is named master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'

  - script: |
      # pip install -r requirements.txt   # uncomment if you have requirements.txt
      python news_now.py                  # replace with your Python file name
    displayName: "Run Python Script"
